### ISSUE TITLE
Procedural generation causes bones to spawn all at same location

### ISSUE THREAD

**Issue by kevinjycui** [nicktstewart/McGameJam#2]
To reproduce: During the `Digging` scene, there is a high chance that there will be a procedurally generated chunk of 4 gold blocks oriented in a zig-zag shape (like the Z-Block in Tetris) surrounded by stone blocks in which all 4 gold blocks contain fossils (this has been the case for 2 consecutive playthroughs). Unsure if this is intended or not but this occurrence makes the game extremely easy.

Similar example with 3 bones:
![image](https://user-images.githubusercontent.com/38621453/158543313-69537569-1823-4ed4-90ae-59a2e5c340d9.png)

This issue in turn also highlights that if the player does not pick up the bones, the sprites of the subsequent bones do not change. This behaviour is not *necessarily* unintended.

**Comment by OwlFight** [comment]
Fixed in last commit.
Generation should be giving out 4 MAX in a clump (very rare tho)
To play with the clumps go on grid, and change the scale variable on the TerrainGeneration script.
