### ISSUE TITLE
Digging dirt too quickly gets the player stuck

### ISSUE THREAD

**Issue by kevinjycui** [nicktstewart/McGameJam#3]
To reproduce: Enter `Digging` scene and spam any direction (e.g. spam the `A` key) such that the player digs through a line of **dirt** blocks. After breaking two dirt blocks, the player becomes unresponsive to input and the game is unplayable.

**Comment by OwlFight** [comment]
last commit fixed it.
it was a problem with the player detecting the shadow as a block, and being un able to break it.
